apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadfvlg2116-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadfvlg2116-tenant-component
    app.kubernetes.io/part-of: loadfvlg2116-tenant-app
  name: loadfvlg2116-tenant-component
  namespace: loadfvlg2116-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadfvlg2116-tenant-component
    weight: null
status: {}
